options:
  - description: "add VSCode workspace config"
    key: VSCode workspace
    steps:
      - description: "linking config file to PegboardHub directory"
        links:
          ~/git/pegboardhub/Pegboard.code-workspace: assets/Pegboard.code-workspace
        